### ISSUE TITLE
Comentários

### ISSUE THREAD

**Issue by campiolo** [dsambugaro/DBG#1]
- Detalhar a interface (entrada, saída, erros)
- Para ficar mais claro, qual é o fluxo de dois jogadores desde a conexão até o encerramento da partida?
- Como o Kafka será usado na aplicação de vocês?

**Comment by dsambugaro** [comment]
Documentação foi atualizada contendo maior detalhes e ilustrações de fluxo. 
A documentação pode ser encontrada [aqui](https://github.com/dsambugaro/DBG/blob/master/Docs/documentation.md)
